// export const baseUrl = 'http://localhost:8080';
export const baseUrl = 'http://file-upload.ubncloud.com';
export const endpointSubmit = baseUrl+'/submit';
export const endpointUpload = baseUrl+'/upload';
export const endpointData = baseUrl+'/data';
export const autoUpdates = true;
export const updateInterval = 10*1000;
export const appendDataImmediately = false;
export const formValidationEnabled = true;